### ISSUE TITLE
ATP-dependent protein disaggregase activity

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#101]
GO:0140545   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0140545/complete)
ATP-dependent protein disaggregase activity
Molecular Function

needs has-input option in canto

**Comment by kimrutherford** [comment]
What should "has_input" display as in Canto?

**Comment by ValWood** [comment]
I think a disaggregase is classed as a chaperone, so "chaperones"

**Comment by kimrutherford** [comment]
Thanks.  I've changed the extension configuration.  If you need it today, I'll update the Canto ontologies again once the current update for FYPO finishes.  Easy to do - up arrow and return :-)

**Comment by kimrutherford** [comment]
>  I'll update the Canto ontologies again once the current update for FYPO finishes.

It's updating now.  Should be done by 12:40 or so.
