### ISSUE TITLE
News item PombeTalks

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#12]
Virtual PombeTalks, Wednesday the 29th of April at 17:00 Central European Time (8:00 San Francisco, 11:00 NY, 16:00 London,  20:30 Delhi, 23:00 Singapore/China, 24:00 Japan).

Aleksandar Vjeṧtica, Sophie Martin’s lab, University of Lausanne
Cycling for reproductive fidelity: Coupling the cell cycle and re-fertilisation blocks ensures ploidy maintenance during sexual lifecycle

Haitong Hou, Julia Cooper’s lab, NCI, NIH/ University of Colorado
Centromeres are dismantled by foundational meiotic proteins Spo11and Rec8

To attend, join pombelist or @PombeSlack for the Zoom link details.
Mark your calendar for the next two on May 13 and May 27! Same place, same time.

If you would like to speak at a future session, please fill out this form https://docs.google.com/forms/d/e/1FAIpQLSdjnkJfadUwM2eKIBJBQXeLt3aOfzrQEb3D8lvNym1g93DIRQ/viewform

**Comment by ValWood** [comment]
thumbnail

<img width="447" alt="Screenshot 2020-04-22 at 16 19 00" src="https://user-images.githubusercontent.com/7359272/80000544-2dc42e00-84b5-11ea-8674-1c00c13b89c9.png">

**Comment by mah11** [comment]
Actually, news items do go on the website tracker, because they need a page per item to be created.

Also, you can move tickets between trackers within one project now - "Transfer issue" at the bottom of the right-hand list.
