### ISSUE TITLE
new extension option for phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#14]
could all of the terms with 
"homologous chromosome pairing at cis-acting homologous chromosome pairing region"

e.g.
FYPO:0003054 | decreased homologous chromosome pairing at cis-acting homologous chromosome pairing region

have a configuration options to add occurs_at (gene/locus)
So I can add 
sme2 etc?

**Comment by ValWood** [comment]
also how can we configure so that I can specify which foci?



mei2 | mei2Δ | FYPO:0007357 | Smp focus absent from cell | Microscopy |   | A55 locus. fig2 |   | 
omt3 | omt3Δ | FYPO:0007357 | Smp focus absent from cell | Microscopy |   | A55 locus. fig2 |   | 
lncRNA584 | SPCC1919.05-antisense-2Δ | FYPO:0007356 | normal Smp focus formation | Microscopy |   | C24 locus. fig2 |   | 
ski3 | ski3Δ | FYPO:0007357 | Smp focus absent from cell | Microscopy |   | C24 locus. fig2 |

**Comment by ValWood** [comment]
I don't see the options yet @kimrutherford  should I?

**Comment by kimrutherford** [comment]
I think the nightly ontology update isn't always getting an up to date version of the extension configuration.  I'll investigate more tomorrow.  For now I've restarted the ontology load in the background so I'm hoping you'll see the new extension option in a bit over an hour.

New issue: https://github.com/pombase/canto/issues/2284

**Comment by ValWood** [comment]
also need this option on the corresponding normal terms

eg. FYPO:0007353

**Comment by ValWood** [comment]
FYPO:0007354
has "assayed region" but  I can't add a locus (I can  for FYPO:0007350)

**Comment by mah11** [comment]
wait for the update that will fetch the currently-10-minute-old commit (bleat again if it still doesn't work after that)
