### ISSUE TITLE
new research spotlight, Ding

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#16]
{
"title": "Ding et al., 2020",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/2020-05-05-31811152"],
"content": "Chromosome-associated RNA-protein complexes promote pairing of homologous chromosomes during meiosis.\nOriginally published in Nat Commun.",
"reference_id": "PMID:31811152,
"link_label": "Publication record in PomBase ...",
"date_added": "2020-05-05",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
I uploaded the image from an accompanying review because it summarized nicely

**Comment by ValWood** [comment]
session is now approved

**Comment by kimrutherford** [comment]
Should be visible on Thursday.
