### ISSUE TITLE
spotlight Muñoz et al., 2020

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#17]
{
"title": "Muñoz et al., 2020",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/2020-05-06-PMID_32277274"],
"content": "Conserved roles of chromatin remodellers in cohesin loading onto chromatin.\nOriginally published in Current Genetics.",
"reference_id": "PMID:32277274,
"link_label": "Publication record in PomBase ...",
"date_added": "2020-05-06",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
I cant commit the image to the repo right now, will try later
<img width="364" alt="2020-05-06-PMID_32277274" src="https://user-images.githubusercontent.com/7359272/81184231-12bee700-8fa8-11ea-9b42-d3988718b3c3.png">

**Comment by kimrutherford** [comment]
Is this Spotlight ready to go once the image is in the repo?

**Comment by ValWood** [comment]
Yes, I'll try again now

**Comment by ValWood** [comment]
AH got it. For some reason it works on the  new laptop but not the old one...

**Comment by ValWood** [comment]
this one can go live

**Comment by ValWood** [comment]
this one isn't appearing.

**Comment by mah11** [comment]
look at the datestamp; raise on website tracker if the delay is unexpected

"Last updated 2020-05-06: ..."
