### ISSUE TITLE
Obsolete term in the process slim

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-config#19]
This term is obsolete so the web site can't be updated for now:

```json
      {
        "name": "cofactor metabolic process",
        "termid": "GO:0051186"
      }
```

https://www.ebi.ac.uk/QuickGO/term/GO:0051186

**Comment by ValWood** [comment]
Oh sorry there is a new Pombase slim
https://github.com/geneontology/go-ontology/issues/19253
The pombe slim is updated. Do you need to do something locally?

**Comment by kimrutherford** [comment]
The slim terms are in our config file because it was easier to implement in a hurry for the new site.  I'll make the changes from the GO issue and see how it looks.

**Comment by kimrutherford** [comment]
This slim looks OK to me.  Let me know if there are problems.

**Comment by ValWood** [comment]
Yep, great!
