### ISSUE TITLE
replacement image

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#20]
I just uploaded a different image for
2020-05-05-31811152-chr-associated-rna-protein-meiosis.png

<img width="339" alt="2020-05-05-31811152-chr-associated-rna-protein-meiosis" src="https://user-images.githubusercontent.com/7359272/81657976-42e70980-9430-11ea-8e69-21efb023e60d.png">

but I am not sure that it worked

**Comment by kimrutherford** [comment]
Thanks.  I've tweaked the dimensions to 300x185.  The main site will updated soon.
