### ISSUE TITLE
Extension relations needing a priority

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-config#23]
There are a bunch of warnings in the log file for website generation:
https://curation.pombase.org/dumps/builds/pombase-build-2020-06-01/logs/log.2020-06-02-00-16-04.web-json-write

There are 4 new extension relations that don't have the priority configured for creating the "target of" section on gene pages:
 - activity regulated by
 - transcription activated by
 - transcription regulated by
 - transcription repressed by

They are defaulting to the lowest priority.

The current configuration is here:

https://github.com/pombase/pombase-config/blob/70746c64e7c4a12025bd63195c4fb5afd322dff9/website/pombase_v2_config.json#L3280-L3292

See: https://github.com/pombase/website/issues/299

**Comment by mah11** [comment]
Yep, I added the new display relations, as an offshoot of #22. I don't know what @ValWood wants their priority to be.

**Comment by ValWood** [comment]
I guess

 "directly activated by": 20, 
   "directly inhibited by": 20, 
   "phosphorylated by": 15, 
   "ubiquitinated by": 15,
->activity regulated by 
   "substrate of": 9, 
   "binds": 8, 
   "transported by": 7, 
   "localized by": 6, 
- >transcription activated by
-> transcription repressed by
- > transcription regulated by
   "regulated by": 6, 
   "activity affected by mutation in": 5, 
   "affected by mutation in": 4 

I don't want to edit  it because I don't know what the number are?

**Comment by kimrutherford** [comment]
They're arbitrary priority numbers.  They can be anything as long the the higher priority extensions have higher numbers.  

```
 "ubiquitinated by": 15,
 ->activity regulated by
 "substrate of": 9,
```

So "activity regulated by" needs a priority number between 9 and 15 if you want it to have a higher priority that "substrate of" and a lower priority than "ubiquitinated by",

```
   "localized by": 6, 
- >transcription activated by
-> transcription repressed by
- > transcription regulated by
   "regulated by": 6, 
```

If you want three to have the same priority as "localized by" and "regulated by" we can put them at 6.  If you want them to have higher priority than "regulated by" or lower priority than "localized by" we'll need to shuffle the numbers around a bit.

**Comment by ValWood** [comment]
higher than regulated by (more specific)
lower than localized by (less direct)

**Comment by kimrutherford** [comment]
Thanks.

Changed to this for today's load:

```
     "relation_priority": {
       "directly activated by": 20,
       "directly inhibited by": 20,
       "phosphorylated by": 15,
       "ubiquitinated by": 15,
       "activity regulated by": 13,
       "substrate of": 11,
       "binds": 10,
       "transported by": 9,
       "localized by": 8,
       "transcription activated by": 7,
       "transcription repressed by": 7,
       "transcription regulated by": 7,
       "regulated by": 6,
       "activity affected by mutation in": 5,
       "affected by mutation in": 4
     }
```
