### ISSUE TITLE
Add to MF slim

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#26]
Only a small number of annotation but for now needs to be included. May remove later
GO:0047429

**Comment by ValWood** [comment]
and
phosphotransferase activity, for other substituted phosphate groups (GO:0016780)

**Comment by ValWood** [comment]
topological DNA entrapment activity (GO:0061776)

**Comment by kimrutherford** [comment]
I added those in time for the nightly load: https://www.pombase.org/browse-curation/fission-yeast-mf-go-slim-terms
