### ISSUE TITLE
new spotlight file coulon

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#27]

**Comment by ValWood** [comment]
This is the image but I can't seem to commit it. I keep getting the message "Add some files to include in this commit."


<img width="597" alt="2020-10-06-31980821" src="https://user-images.githubusercontent.com/7359272/86799113-7a0d1c00-c069-11ea-8a3c-e1ad1524b2bb.png">

**Comment by ValWood** [comment]
ah, use the other laptop...

**Comment by ValWood** [comment]
needs checking

**Comment by kimrutherford** [comment]
I tweaked a few things.  It's now on the main site.

**Comment by ValWood** [comment]
thanks
