### ISSUE TITLE
GO:0030674	protein-macromolecule adaptor activity/ recruits

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#29]
recruits isn't going to work for all 
GO:0030674	protein-macromolecule adaptor activity

I'm annotating  nse4 (smc5/6 thing)

It is describes as a "linker" so I am going to use "protein-macromolecule adaptor activity"
and "recruits " won't be correct.

We will need  to specify  which children of 
GO:0030674	protein-macromolecule adaptor activity
"recruits" can apply to

I think it is OK for
GO:0140463   chromatin adaptor
GO:0140312    cargo adaptor activity
GO:0008093    cytoskeletal anchor activity
GO:0005484    SNAP receptor activity
GO:0140483    outer kinetochore adaptor activity
GO:1990756    ubiquitin ligase-substrate adaptor activity
GO:0043495    protein-membrane adaptor activity
GO:0035591    signaling adaptor activity

does that sound reasonable?

**Comment by mah11** [comment]
I don't have preferences in this area. Just decide which branches should use 'recruits', and -- critically -- what to display for branches that don't use 'recruits'.

For example, GO:0043495 uses 'anchors'.

**Comment by ValWood** [comment]
GO:0140463 chromatin adaptor.  - recruits
GO:0140312 cargo adaptor activity - recruits
GO:0008093 cytoskeletal anchor activity -anchors
GO:0005484 SNAP receptor activity- recruits
GO:0140483 outer kinetochore adaptor activity -recruits
GO:1990756 ubiquitin ligase-substrate adaptor activity - recruits
GO:0043495 protein-membrane adaptor activity - anchors
GO:0035591 signaling adaptor activity - recruits

For others  (especially the parent) we can leave as has_input  for now

**Comment by mah11** [comment]
Looks like I only did the Canto config for #24. This time I've done the website display config as well.
