### ISSUE TITLE
if_descendant_of question

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-config#31]
In the "extension_display_names" section of the config file we have examples like:
```json
     {
       "rel_name": "has_regulation_target",
       "if_descendant_of": "GO:0000976",
       "display_name": "regulates transcription of",
       "reciprocal_display": "transcription regulated by"
     }
```

At the moment the code that processes this assumes that "if_descendant_of" means an is_a descendant.  Should it be looking at part_of relations too?

**Comment by mah11** [comment]
Good question. I think it'll be OK to carry on just using is_a for these (it's a bit different from the GO term-gp relation business, because it's just for our extension displays).

**Comment by kimrutherford** [comment]
OK, thanks.  It's easy enough to change it in future if needed.
