### ISSUE TITLE
occurs_at display label

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#37]
Could we change this to "at"

https://user-images.githubusercontent.com/7359272/95987805-d6799780-0e1f-11eb-9241-bb6bda840243.png

it would read better than occurs at which sometimes sounds a bit weird.

**Comment by mah11** [comment]
Canto, website, or both?

**Comment by ValWood** [comment]
I was only thinking about the website.

In Canto it might be a useul indicator of what  datatype the "at"  refers to , but in the website this isn't necessary as the  term is  there to see. So perhaps only website for now?

Also applys to occurs_in/in
