### ISSUE TITLE
SPOTLIGHT fft3

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#4]
PMID: 31575705

Chromatin remodeler Fft3 plays a dual role at blocked DNA replication forks

Ait-Saada et al., 2019

Originally published in Life Sci Alliance

<img width="302" alt="Screen Shot 2020-03-03 at 13 26 27" src="https://user-images.githubusercontent.com/7359272/75780370-20ab7e00-5d53-11ea-9606-bfd35f2093e7.png">

**Comment by kimrutherford** [comment]
That's live now.
