### ISSUE TITLE
PHI-Canto needs 'innate immune response' in domain of occurs_in

### ISSUE THREAD

**Issue by jseager7** [pombase/pombase-config#40]
Some time ago, the PHI-Canto team decided to stop maintaining their own GO extension configuration, and started sharing PomBase's configuration instead (since almost all of the config was the same).

However, we've found one case where the PomBase configuration is insufficient: we can't use occurs_in on the term 'innate immune response' ([GO:0045087](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0045087)). In the curation session for [PMID:15096512](https://canto.phi-base.org/curs/babb18b437174938/ro), the occurs_in extension has been added as text, but this results in syntax errors when trying to submit GAF files to GO.

I realise the domain term is probably only relevant to PHI-base, and it's definitely not ideal to add it to the shared config, but previous discussion in pombase/canto#2276 indicated that Canto would need code changes to allow PHI-Canto to override PomBase's configuration on a term-by-term basis. If PHI-base only needs to change a few extensions, then it may not be worth the effort of implementing a full configuration override system. Also, @ValWood previously suggested that the taxon restrictions in PomBase will hide irrelevant GO terms (although that suggestion was in reference to extension _range_ terms in pombase/canto#2276, so I don't know if the same thing will apply here).

If there are no objections, I'm happy to make a pull request applying the necessary configuration changes.

**Comment by ValWood** [comment]
It's fine to add this to the generic config. This will be hidden from PomBAse users by a taxon restriction.

Val

**Comment by jseager7** [comment]
I've just checked the configuration for occurs_in, and it looks like all of terms in the existing extension ranges are PomBase-specific:

Domain ID|subset relation|extension relation|range ID|Canto display text|Help text|cardinality|role
---|---|---|---|---|---|---|---
GO:0006897|is_a|occurs_in|GO:0032153\|GO:0051286|occurs at||0,1|user
GO:0007015|is_a|occurs_in|GO:0005826\|GO:0051286|occurs at||0,1|user
GO:0071786|is_a|occurs_in|GO:0005938\|GO:0034399|occurs at||0,1|user

Here's the labels for the terms:

- GO:0032153 'cell division site'
- GO:0051286 'cell tip'
- GO:0005826 'actomyosin contractile ring'
- GO:0005938 'cell cortex'
- GO:0034399 'nuclear periphery'

In PHI-Canto's case we need, at a minimum, 'apoplast' (GO:0048046) in the range of the occurs_in extension for 'innate immune response'. I could restrict the extension to that one term, but maybe it would be better if the range was more generic, for example 'cellular anatomical entity' or even the whole of 'cellular component'. That only makes sense if an immune response can occur in any cellular component, though.

**Comment by ValWood** [comment]
I don't see any problem with using  'cellular anatomical entity'  with
GO:0044419    interspecies interaction between organisms
if that is what you mean?

**Comment by jseager7** [comment]
> I don't see any problem with using 'cellular anatomical entity' with
GO:0044419 interspecies interaction between organisms
if that is what you mean?

I was planning to use GO:0045087 'innate immune response' as the domain, but the parent term GO:0044419 'interspecies interaction between organisms' is a better choice for being more general. Thanks for the suggestion. I'll open a pull request to add the extension.
