### ISSUE TITLE
Check the configuration on each commit

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-config#42]
(I've already done this but I thought I should make issue to record the details and for attaching screenshots)

To help avoid mis-configuring the website I've set up some checking of the config files that will run after each change.  The checks are very basic for now but I'll improve them over time.

Currently it checks the JBrowse table ([pombase_jbrowse_track_metadata.csv](https://github.com/pombase/pombase-config/blob/master/website/pombase_jbrowse_track_metadata.csv)) to make sure each line has the correct number of columns.

And it checks the main website config ([pombase_v2_config.json](https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json)):
  - makes sure that it is correctly formatted JSON
  - checks that all the images configured in the Spotlights exist in the right place in the website repository (in the [assets](https://github.com/pombase/website/tree/master/src/assets) directory)

This works by using a new GitHub feature called "Actions".  After each commit a small Perl script runs to do the checks.  If that checking fails you'll get an email from GitHub.  To tests things and to get an example email, I just changed an image path in the config to be a non-existent file with a commit message of "Mangle a image path to check the test Action".
Here is the email I got:

```
From: Kim Rutherford <notifications@github.com>
To: pombase/pombase-config <pombase-config@noreply.github.com>
Reply-To: pombase/pombase-config <noreply@github.com>
Cc: Ci activity <ci_activity@noreply.github.com>
Date: Wed, 28 Oct 2020 16:44:10 -0700
Subject: [pombase/pombase-config] Run failed: Tests - master (ec170b4)

Run failed for master (ec170b4)

Repository: pombase/pombase-config
Workflow: Tests
Duration: 2 minutes and 31.0 seconds
Finished: 2020-10-28 23:43:57 UTC

View results: https://github.com/pombase/pombase-config/actions/runs/334732145

Jobs:
  * build failed (1 annotation)
```

If you follow the link in the email (https://github.com/pombase/pombase-config/actions/runs/334732145) you'll get to:

![actions-1](https://user-images.githubusercontent.com/90474/97512105-91439100-19ed-11eb-991e-808785f897b8.png)

If you click on "build" on the left, then click on whatever has a red cross on the right, you'll see any errors:

![actions-2](https://user-images.githubusercontent.com/90474/97512204-cfd94b80-19ed-11eb-9ac1-2263e2c1dbb2.png)

**Comment by ValWood** [comment]
very cool!

**Comment by kimrutherford** [comment]
> very cool!

:-)

I think it will help reliability a bit.

I want to add a few more basic config checks so I'll leave this issue open for now.

Today I also moved the tests for all the other code repositories to GitHub Actions so they're all in one place.  For example, here are the Canto tests:  https://github.com/pombase/canto/actions?query=workflow%3A%22Canto+tests%22

**Comment by kimrutherford** [comment]
This is done for now.
