### ISSUE TITLE
configuration for term ordering, active form

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#45]
detail view
has input dis2 part of G2/M transition of mitotic cell cycle in mitotic spindle pole body active form cut12/UnMod:(T75,T78) during mitotic G2 phase

will become
active form cut12/UnMod:(T75,T78) has input dis2 part of G2/M transition of mitotic cell cycle in mitotic spindle pole body  during mitotic G2 phase

@kimrutherford  you said not to open a ticket but it didn't appear yet.

I think it might also be good to show the active from in the default view (currently we hide it, but it's important, and now it has a legible label....)

**Comment by kimrutherford** [comment]
After making these changes the MF summary on cut12 page will look like this.  Is that OK?:

![active-form-1](https://user-images.githubusercontent.com/90474/98760041-46873780-2437-11eb-995f-4a9cda21f0ce.png)

**Comment by ValWood** [comment]
Perfect!

**Comment by kimrutherford** [comment]
Great.  I'll update the main site and then close the issue.
