### ISSUE TITLE
too many extension options

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#46]
increased protein kinase activity

some of these seem to be redundant with each other.

<img width="579" alt="Screenshot 2020-11-13 at 15 56 11" src="https://user-images.githubusercontent.com/7359272/99092472-140d4400-25c9-11eb-9159-939829388eb4.png">

**Comment by mah11** [comment]
The last three (`assayed enzyme complex`, `assayed substrate (protein complex only)`, `assayed protein isoform`) are admin-only, and Canto is not clever enough to suppress a user-level extension option if there's a relevant admin option. If it were, I could futz with the admin options to make sure we don't lose any, but for now it's a lot easier just to remember that users are spared most of this cruft.

There's some related information in [this old Canto ticket](https://github.com/pombase/canto/issues/1068) and [this one](https://github.com/pombase/canto/issues/1316).

I have committed a config change that I hope will remove "assayed protein" from the user list. That's all that we can realistically do until Kim has time to do the Canto stuff noted above, so if it works I'll close this.

**Comment by ValWood** [comment]
ah OK, no bother if it's adminonly. I thought it might be confusing for users
