### ISSUE TITLE
PRO IDs not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#47]
https://www.pombase.org/gene/SPBC649.05
didI forget to do something wit these PRO IDS?

active form cut12/UnMod:(T75,T78) 
active form cut12/Phos:(T75,T78)

**Comment by ValWood** [comment]
and some new ones today
https://github.com/PROconsortium/PRoteinOntology/issues/211

**Comment by ValWood** [comment]
PROconsortium/PRoteinOntology#209

**Comment by ValWood** [comment]
https://github.com/PROconsortium/PRoteinOntology/issues/205
https://github.com/PROconsortium/PRoteinOntology/issues/201

**Comment by kimrutherford** [comment]
How should they look?

**Comment by ValWood** [comment]
They look OK but the link outs aren't working. I think they just need adding to a mini-ontology  but I'm not sure where it is. I need to find out  how to do this but for now M.  is doing it....

**Comment by kimrutherford** [comment]
> I think they just need adding to a mini-ontology but I'm not sure where it is. 

I checked the first two and Midori has already added them.

Are they new IDs?  Maybe the PRO website hasn't been updated since they were added to PRI?  The PRO website says: "Current release: 61.0, August 18, 2020"
