### ISSUE TITLE
Modified form

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#49]
needs adding to some file?

PR:000050481

https://github.com/PROconsortium/PRoteinOntology/issues/222#issuecomment-751784749

**Comment by kimrutherford** [comment]
I've added to the end of pombe/pombe-embl/mini-ontologies/pombe_mini_PR.obo in SVN.  The name will need tweaking by Midori.

**Comment by ValWood** [comment]
also
PR:000050484 rng2/Phos(S199/S207)
https://github.com/PROconsortium/PRoteinOntology/issues/223#issuecomment-754127974

**Comment by mah11** [comment]
all done
