### ISSUE TITLE
severity qualifier

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#5]
Is not available for
FYPO:0006822 | viable small vegetative cell with normal cell growth rate

**Comment by mah11** [comment]
I don't understand why it's not showing up - the config looks like it should offer severity for anything with a path to abnormal via is_a or has_part links (FYPO:0006822 doesn't have an all-is_a path but does have a path including has_part).

@kimrutherford any clue? config line is 

    FYPO:0001985-is_a(FYPO:0005446)&is_a(FYPO:0005448)	is_a|has_part	has_severity	FYPO_EXT:1000001	severity		0,1	user

**Comment by ValWood** [comment]
I'm sure that I saw a fix for this GO by? was it in another ticket?

**Comment by kimrutherford** [comment]
I've just tried this and I was able to make an annotation to FYPO:0006822 "viable small vegetative cell with normal cell growth rate" with a severity qualifier in the main pombe Canto.

Could you double check?

**Comment by mah11** [comment]
working nicely for me too
