### ISSUE TITLE
has_input

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#50]
enable  has_input to “protein folding chaperone”

**Comment by ValWood** [comment]
I keep forgetting where these files are now....

**Comment by mah11** [comment]
Kim documented it in the [Canto wiki](https://github.com/pombase/canto/wiki/AnnotationExtensionConfig)

**Comment by ValWood** [comment]
I added a row to the file using the git editing interfaces. Something is wrong here because  although I am making a tab in the first column it is saving as a space. I change to a tab and it won't let me save. I can save if I add 2 tabs then delete one, but the formatting looks screwy so I think it might not parse...

**Comment by kimrutherford** [comment]
I've changed the spaces to tabs.

**Comment by ValWood** [comment]
I don't know why this happens, I guess I need to use the c-line version.
