### ISSUE TITLE
improve prompt for  location of  MF extension

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#57]
I have been wondering if we could come up with a better label than "active in"
for this prompt.

It seemed weird in this context (vacuolar membrane) and so if I was a user I don't think I would click on 'active in' to capture this information. Also it probably wont occur to people to use it for the 'passive' molecular functions like anchors and adaptors.

<img width="515" alt="better label than active in" src="https://user-images.githubusercontent.com/7359272/107413477-b2497100-6b08-11eb-8f2f-56b77521d839.png">

I don't have any great suggestions  but  I almost prefer the "occurs in" but that would also be odd in some contexts.

Would it be crazy to say
"occurs in/at"
or  even "occurs at location"

**Comment by mah11** [comment]
how about "physical location"?

**Comment by ValWood** [comment]
I like that much better!

**Comment by ValWood** [comment]
Another one here:
can this "has regulation target" display label be just "regulates" or  even "activates" or "inhibits"

https://www.pombase.org/gene/SPBC337.13c

**Comment by mah11** [comment]
> (display label on the gene page, not in Canto, so is this the wrong tracker?)

right tracker, since both displays are configured in ... wait for it, config files

**Comment by mah11** [comment]
https://github.com/pombase/pombase-config/commit/e73b4d071af1380df7573548c51bec5b495f6f1b is for this (mistyped ID in commit blurb)
