### ISSUE TITLE
 GO extension config update for PHI-base

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#58]
Since PHIBase are sharing our GO config  (unless it becomes impractical for some reason)

Can we add
GO:0051707 response to other organism

for 'during' extensions MF,BP,CC

(it should not show for us as it has a taxon restriction "never in Sz."

@jseager7 
@CuzickA

**Comment by kimrutherford** [comment]
> Can we add
> GO:0051707 response to other organism
> for 'during' extensions MF,BP,CC

I've added it for happens_during.  I hope that's what you meant.
