### ISSUE TITLE
spotlight  (mcp1) (video)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#6]
[JCB_201901108_V1.mp4.gz](https://github.com/pombase/pombase-config/files/4331082/JCB_201901108_V1.mp4.gz)

**Comment by ValWood** [comment]
{
"title": "Chacko et al., 2020",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/2020-03-23-31582398_mcp5.mp4"],
"content": "Cortical tethering of mitochondria by the anchor protein Mcp5 enables uniparental inheritance\nOriginally published in J Cell Biol.",
"reference_id": "PMID: 31582398 ",
"link_label": "Publication record in PomBase ...",
"date_added": "2020-03-23",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
@kimrutherford Could you handle this one. It's a video and will require renaming. I'm not sure if anything special is needed for videos?

Will be live tomorrow.

**Comment by kimrutherford** [comment]
> Could you handle this one. It's a video and will require renaming. I'm not sure if anything special
> is needed for videos?

The video will need to be scaled to 300x185 pixels.  I'll try that tomorrow.

**Comment by ValWood** [comment]
At the same time could you restrict the spotlights to those since
2020-02-29?

**Comment by kimrutherford** [comment]
Done!
