### ISSUE TITLE
Asssayed region for protein localization to chromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#63]
abnormal protein localization to chromatin (FYPO:0001679)

add extension option  for "assayed region' which can be a SO term of a gene

Does that sound OK?

**Comment by ValWood** [comment]
These terms appear and I used them, but I still had to add in text mode because assayed_protein and assayed region are mutually exclusive, so once you use one the other is greyed out.

**Comment by mah11** [comment]
I've made some adjustments that I hope will fix it ... seems to have something to do with paths so I'm winging it a bit.
