### ISSUE TITLE
more explicit FYPO extension relations

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-config#65]
Related to #63 and https://github.com/pombase/pombase-chado/issues/828

I could do a quick fix for the item in the Chado ticket, but I had a bit of a think. Now I wonder if we should make the FYPO extension relations more explicit globally, since Canto treats GeneID, TranscriptID, and ProteinID identically (and I managed to forget that it does that, & jsut looked at the range entries and thought "that oughta be fine"). It would be more consistent overall than futzing around the edges for one case (and then another, and another ...).

We could use `assayed_region`, `assayed_transcript`, and `assayed_protein` for GeneID, TranscriptID, and ProteinID respectively. Some of the SO ranges would also get `assayed_region` or `assayed_transcript`.

I've added all three to fypo_extension_relations.obo on spec, and will edit the FYPO extension configuration soon(ish) if you like the idea. @kimrutherford could you remind me whether the website config would need any changes?

Thoughts?

**Comment by ValWood** [comment]
This sounds much better.

**Comment by mah11** [comment]
OK, I've committed a big ol' overhaul, and added relations to the pombase-legacy `load-pombase-chado.yaml` file. I'll leave this open until Kim has a chance to see if the load goes well.

**Comment by kimrutherford** [comment]
Thanks.  I'll keep an eye on the load.

I think line 8 of load-pombase-chado.yaml is a typo?
```
assayed_using
```

https://github.com/pombase/pombase-legacy/commit/e5f1ea15280110dae64c866e7d3448871cdca3f9#diff-0c66eb5b988dac95a4640dd17b66d28c7ba1e0873bfd9ef7a3e1b4dcb6635d0fR8

**Comment by mah11** [comment]
> I think line 8 of load-pombase-chado.yaml is a typo?

must be - I don't remember editing that line! Could've been a slip of the mouse. Want me to fix it or will you?

**Comment by kimrutherford** [comment]
I'm happy to fix it.  Does "assayed_using" need to be added to the list of allowed extensions?

**Comment by mah11** [comment]
> I'm happy to fix it.

Thanks!

> Does "assayed_using" need to be added to the list of allowed extensions?

It should already be there - we've been using it for literally years.

**Comment by kimrutherford** [comment]
> It should already be there - we've been using it for literally years.

Ah, right.  I missed it when I had a look.

I've committed the fix and I'll keep an eye on the load.

**Comment by kimrutherford** [comment]
I think this is done now.  https://www.pombase.org/reference/PMID:33771877 looks OK.
