### ISSUE TITLE
has_input for GO:0004861 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#66]
GO:0004861 | cyclin-dependent protein serine/threonine kinase inhibitor activity
has no has_input option in canto

**Comment by mah11** [comment]
First, enquire with GO as to why the ontology doesn't have these links:

- enzyme activator activity (GO:0008047) is_a enzyme regulator activity (GO:0030234)
- enzyme inhibitor activity (GO:0004857) is_a enzyme regulator activity (GO:0030234)

It would make our lives easier if the specific activator and inhibitor MF terms could inherit from the existing config we have for GO:0030234.

**Comment by ValWood** [comment]
odd, will do...

**Comment by mah11** [comment]
Is this behaving as expected now? I get offered `regulates activity of` in Canto.

**Comment by mah11** [comment]
They'll all be kept as, or converted to, `has_input` for the GAF & GPAD we send to GO, so I think it's up to you whether you want to change any extension relations for our internal use. It might be a good idea, because it'll make our webpage displays easier to understand.

**Comment by ValWood** [comment]
Good point.Can we change the display label to "inhibits"?

I can't remember why some display as has_input and some as 
"regulates activity of"

**Comment by ValWood** [comment]
display label should work on "enzyme inhibitor activity"once: https://github.com/geneontology/go-ontology/issues/21398

**Comment by mah11** [comment]
The original problem here is fixed: Canto now offers the "regulates activity of" extension option for GO:0004861 and various other terms in the "MF regulator" branch of GO.

I'll hive the display stuff off to a separate ticket, because it's website configuration.
