### ISSUE TITLE
has_input

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#68]
on the cut12 page we display has_input.
Should we always display has_substrate if there is no display label (more biologist friendly)?

**Comment by ValWood** [comment]
![Uploading Screenshot 2021-05-14 at 19.43.14.png…]()

**Comment by kimrutherford** [comment]
I'm not sure I understand this bit:

> if there is no display label

The current configuration only displays "has substrate" if the relation is "has_input" and the term is_a "catalytic activity" (GO:0003824).

In this case no special configuration matches so we just show "has input".  (The display code changes underscores to spaces in relation names to make things look nicer)

Are you thinking that we should we display has_input as "has substrate" for "signaling adaptor activity" (GO:0035591)?

**Comment by ValWood** [comment]
yeah ignore. has input isn't very biologist friendly but has substrate might sound weird.

**Comment by kimrutherford** [comment]
Is there a different display text we can use for has_input in this case?  It doesn't have to be "has substrate".

**Comment by ValWood** [comment]
This one is a bit tricky. Not least because it conflates adaptors and scaffolds... anyway it's fine. I'm being picky. We can deal with this later if we get inspired.
