### ISSUE TITLE
Can't distinguish different use of "affecting"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#70]
I can't find  an open ticket for this. Not possible to distinguished between affected protein and affected  region...

<img width="1000" alt="differentiate 'affecting'" src="https://user-images.githubusercontent.com/7359272/120500496-cd423880-c3b8-11eb-9068-5bf2df82c38e.png">

**Comment by mah11** [comment]
changed to "affected region" for (wait for it) `assayed_region`; reopen this if that doesn't suffice

**Comment by ValWood** [comment]
Oh right, I needed to fix it!
