### ISSUE TITLE
extension display for MF regulator terms

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-config#79]
Transferred from #66

For MF regulator extension displays:

> Can we change the display label to "inhibits"? [for inhibitors]

Yes. It'll make the configuration less simple, because separate GO IDs will have to be configured for general, positive (activator), and negative (inhibitor) regulator terms; that also means it'll be a bit more error-prone. But it is feasible in principle.

> I can't remember why some display as has_input and some as
> "regulates activity of"

It depends on what the actual extension relation is behind the scenes.

Anything where the relation is `has_regulation_target` is displayed as 'regulates activity of' (this includes any done via the Canto "regulates activity of" extension option. If the extension was made using `has_input`, *and* no other display string is configured for the "extended" (i.e. annotated; GAF col 5) term, the display is (wait for it) 'has input'.

I checked up on some of the has_input extensions on various MF regulator annotations, and they're a mix of annotations from Artemis/contig files and from older Canto sessions.

I'll add some more entries for `has_input` and `has_regulation_target` to the config.

There are also a few that were done as `has_direct_input`, `directly_negatively_regulates`, or `directly_positively_regulates`, which display as 'has substrate', 'directly inhibits', and 'directly activates' respectively. For the `has_direct_input` extensions I think it could get tangled too easily if we try to change the display, so I'd rather leave them alone or change the extension relation. The directly_regulates ones are probably good enough.

For future reference, web page extension display is configured here (link goes to first line of that part of the cenfig file):
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L3340

... and is documented here:
https://github.com/pombase/website/wiki/Config-file

**Comment by mah11** [comment]
also transferring one more comment from Val:
> display label should work on "enzyme inhibitor activity"once: https://github.com/geneontology/go-ontology/issues/21398

**Comment by mah11** [comment]
and in case it's of interest, uploading a mini-GAF of annotations to MF regulator terms that have extensions
[Uploading MF_regulator_with_extension_gaf.txt…]()

**Comment by ValWood** [comment]
OK thanks. I will try to do the next changes to the extension configuration. I should be able to do this as I did it in the early days. I think some of the configuration might now be quite complex though! we shall see.....
