### ISSUE TITLE
Canto display label for 'epigenetic reader'

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#82]
is 'recruits'
I think this is because 'epigenetic reader is a descendant of 'adaptor'

Although a reader does act as an adaptor, and I guess the reading of a histone mark is part of this activity 
is sounds odd because in this case the histone mark is recruiting the reader. I think this is a GO issue but can we change this label to "reads" in canto (and on website). 

I'll raise the parentage on the next call.

**Comment by mah11** [comment]
Config edits will handle both Canto and website - shout if you want coaching on exactly what to edit (cf. #80).

**Comment by ValWood** [comment]
Yes I still have https://github.com/pombase/pombase-config/issues/80 in my inbox.
Let's see at the beginning of next week the situation with ODK, if not ready we can do this instead.
