### ISSUE TITLE
problems with browser track metadata

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#83]
I was checking the Blevins tracks metadata and noticed an issue with the "Eser" data

~Assayed gene product has **WT**, should be **972h-**~
Strain bachground has **WT**, should be  **?** (probably empty)
WT or mutant  has **...**, should be **WT**
mutant alleles has "YES" should be **...**
conditions has **"..."** should be **YES**

I'm confused as this seems to be generally muddled columns, rather than an off by one error? I will check some more...

**Comment by mah11** [comment]
moving ticket because the metadata file is in pombase-config

**Comment by mah11** [comment]
oh, and "972 h-" is a background, not a gene product

**Comment by ValWood** [comment]
OK if you can fix. A quick glance I can't see any others with issues.

**Comment by ValWood** [comment]
> (unless you want to convert everything to using soon-to-be-FYECO IDs).

That can be a task for new person!
