### ISSUE TITLE
check why 2 relation prompts appearing GEF, and query about GAP relation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#84]
Canto prompt:
guanyl-nucleotide exchange factor activity (GO:0005085)
<img width="226" alt="config ticket relation prompts" src="https://user-images.githubusercontent.com/7359272/147858347-ec623c38-e4a9-4078-a557-e250105b0dae.png">

**Comment by kimrutherford** [comment]
Which term were you adding the extension to?

**Comment by ValWood** [comment]
guanyl-nucleotide exchange factor activity (GO:0005085)
 
I can look at this but I was going to  batch these. I haven't done any of these
Canto prompts yet so feel free to fix...

**Comment by ValWood** [comment]
for Rho1 there are a mixture of 'inverse relationships'
in the target of section.

GEFs have
GO | substrate of | art1 | RhoGEF Art1
GO | substrate of | rgf1 | RhoGEF for Rho1, Rgf1
GO | substrate of | rgf2 | RhoGEF Rgf2
GO | substrate of | rgf3 | RhoGEF or Rho1, Rgf3

GAPs have a mixture, implying a mixture of forward relationships
GO | activity regulated by | rga1 | RhoGAP, GTPase activating protein Rga1
GO | substrate of | rga8 | RhoGAP, GTPase activating protein Rga8
GO | regulated by | rga5 | RhoGAP, GTPase activating protein Rga5

**Comment by ValWood** [comment]
we should look at this on next call, we still have 2 relations

**Comment by kimrutherford** [comment]
I'm confused.  Is this a Canto config issue or the website?  Or both?

**Comment by ValWood** [comment]
I pn;y looked at Canto, there are 2 extension prompts for this term. We can look next week, no hurry
v

**Comment by kimrutherford** [comment]
I've updated the configuration to remove regulates for GO:0005085.  The change will be visible in Canto in an hour or so.
