### ISSUE TITLE
protein serine/threonine phosphatase display label ->dephosphorylates

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#85]
https://www.pombase.org/term/GO:0016791

<img width="495" alt="Screenshot 2022-01-30 at 08 52 39" src="https://user-images.githubusercontent.com/7359272/151791051-11fcb62f-561a-45d7-a20c-42f5e824ed70.png">

**Comment by kimrutherford** [comment]
No problem.  Should it say "dephosphorylated by" in the "Target of" table of the substrate?

**Comment by ValWood** [comment]
Yes please!

**Comment by kimrutherford** [comment]
I've added that to the configuration.  I'll check in the morning.

After changing the config I noticed a bug: pombase/website#1831
