### ISSUE TITLE
fix config to show the same relation for assayed enzymes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#87]
<img width="728" alt="Screenshot 2022-11-11 at 11 13 25" src="https://user-images.githubusercontent.com/7359272/201338686-1a780ae0-f47b-4381-ac5a-d73d601662de.png">

one branch has  "assayed enzyme"
one branch has "affecting activity of"
(I think "affecting activity of" is probably more meaningful to explain the context)?

**Comment by kimrutherford** [comment]
It took a while to work this one out.  The configuration and ontologies were all OK.  There was a bug in the code that processed the extensions of the single allele phenotypes.  Fixed for Wednesday morning.  It will say "affecting activity of" for both then.

**Comment by ValWood** [comment]
wow, its late!

**Comment by kimrutherford** [comment]
Fixed!

![image](https://github.com/pombase/pombase-config/assets/90474/a360ce07-8f46-4bc6-ad0b-3890df0fe318)
