### ISSUE TITLE
spotlight PACS

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#9]
{
"title": "Cabera et al., 2020",
"title_link": null,
"panel_type": "spotlight",
"head_image": ["assets/spotlight/2020-03-20-32075773"],
"content": "Chaperone-Facilitated Aggregation of Thermo-Sensitive Proteins Shields Them from Degradation during Heat Stress.\nOriginally published in Cell Rep.",
"reference_id": "PMID: 32075773",
"link_label": "Publication record in PomBase ...",
"date_added": "2020-04-28",
"show_on_front_page": true
},

**Comment by ValWood** [comment]
the image
This should be through in 2 days, still waiting for GO term

![fx1_lrg](https://user-images.githubusercontent.com/7359272/79873959-b2dd1380-83df-11ea-9740-f41bd146da8b.png)

**Comment by ValWood** [comment]
2020-04-28-Hidalgo-PAC.png 

 in the repository

**Comment by ValWood** [comment]
hopefully I did that correctly!

**Comment by kimrutherford** [comment]
> 2020-04-28-Hidalgo-PAC.png
> in the repository

Which repository?

**Comment by kimrutherford** [comment]
> hopefully I did that correctly!

The only fix was to remove the space after the PMID: in:

      "reference_id": "PMID: 32075773",
