### ISSUE TITLE
Ontology term: nucleocytoplasmic carrier activity (GO:0140142)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#90]
Ontology term: nucleocytoplasmic carrier activity (GO:0140142)

needs a has_input prompt of some sort in canto for the cargo

**Comment by ValWood** [comment]
<img width="906" alt="Screenshot 2023-02-15 at 17 35 06" src="https://user-images.githubusercontent.com/7359272/219450853-3dee717d-44fb-4751-89c2-15251f3bbde4.png">

**Comment by kimrutherford** [comment]
> needs a has_input prompt of some sort in canto for the cargo

What's allowed at the cargo?

**Comment by ValWood** [comment]
Only a gene product

**Comment by kimrutherford** [comment]
Should it say "carries" in the dialog?

**Comment by ValWood** [comment]
that would work...
thanks!

**Comment by kimrutherford** [comment]
> Do you remember why we do this in 2 places?

We keep the Canto config separate so it can be used standalone by external groups.

> which has substrate? so the other parntage branch must 'trump' it?

We only have one "has substrate" configured.  It's for `GO:0003824`:

https://github.com/pombase/pombase-config/blob/6ba0e6b5d0015e8482a84ce1d2586d5fb0ac2377/website/pombase_v2_config.json#L5129-L5134

**Comment by kimrutherford** [comment]
I've added the config for has_input() for GO:0140142.  I'll check the main site on Wednesday morning.

**Comment by ValWood** [comment]
It's there on the website and inCanto. Thanks!
