### ISSUE TITLE
has_regulation_target

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#92]
PMID:27183195 &
PMID:18280239 &
PMID:22323607

GO:0170008 | mRNA phosphatase activator activity | IDA |   | has_regulation_target dcp2

 has_regulation_target is the relation, and display label in Canto.
we can change this to "has_input" as the relation, with the display label
"activates"

**Comment by ValWood** [comment]
PMID:34086083

similarly
GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific
can be has_input with display label "activates transcription of"

but oddly others look like this:
<img width="842" alt="Screenshot 2023-02-24 at 17 38 20" src="https://user-images.githubusercontent.com/7359272/221249575-a7f4ea30-4aa4-4c5e-8996-cd31991f03ea.png">

which is similar to the problem I reported the other day?

**Comment by kimrutherford** [comment]
> GO:0170008 | mRNA phosphatase activator activity | IDA |   | has_regulation_target dcp2
>
> has_regulation_target is the relation, and display label in Canto.
>we can change this to "has_input" as the relation, with the display label "activates"

It now has "regulates activity of" on the GO:0170008 page.  Is that correct or should it be "activates"?

> GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific
> can be has_input with display label "activates transcription of"
>
> but oddly others look like this:

It now says "activates transcription of mug14" on the rst2 page:
https://www.pombase.org/gene/SPAC6F12.02

**Comment by ValWood** [comment]
1. All of the molcular function activators say
 https://www.pombase.org/term/GO:0140677
 "regulates activity of"
- "activates" would be better here.

2. Note to self, there are still some annotations where  the incorrect extension relation is hard-wired in legacy curation, need updating:
jac1, swr1, map2, mmf1-3

**Comment by kimrutherford** [comment]
> All of the molcular function activators say
> https://www.pombase.org/term/GO:0140677
> "regulates activity of"
>
> "activates" would be better here.

This is the current configuration for "regulates activity of":

```json
        {
            "rel_name": "has_input",
            "if_descendant_of": "GO:0030234",
            "display_name": "regulates activity of",
            "reciprocal_display": "activity regulated by"
        }
```

I've changed it to "activates" with reciprocal "activated by".  If that's OK we can close this.

The change will be visible on Tuesday morning.

**Comment by ValWood** [comment]
ATPase activator activity (GO:0001671): appears to be hardwired to  directly_positively_regulates , this should also be activates

**Comment by ValWood** [comment]
GO:0000772 | mating pheromone activity should also be "activates"



[GO:0000772](https://www.pombase.org/term/GO:0000772)	
[mating pheromone activity](https://www.pombase.org/term/GO:0000772)

**Comment by kimrutherford** [comment]
OK, I've added configuration to display "has_input" as "activates" on the website for GO:0001671 and GO:0000772.  And I've added the config so that those extensions can be added in Canto.  The Canto changes will be visible in the morning.  The website will be visible on Thursday morning.

The annotation with directly_positively_regulates in Canto will need to be changed to has_input/activates.
