### ISSUE TITLE
prompt for "catalytic activity regulator"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#93]
Website display prompt for "catalytic activity regulator" branch

<img width="1071" alt="Screenshot 2023-03-10 at 14 17 09" src="https://user-images.githubusercontent.com/7359272/224338990-f573fc94-861a-4193-ba61-06ae42a51b32.png">

we display has_regulation_target
I think this should change to "regulates activity of"

(Canto too possibly, I didn't check this)

@kimrutherford  can you remind me how to do these next week , I think I remember one but not the other

**Comment by ValWood** [comment]
Also we can look at the chaperone prompts:
<img width="617" alt="_canto mis prompt" src="https://user-images.githubusercontent.com/7359272/224493756-e54d3f88-9912-40ce-9e00-9241dcd4c4f8.png">

**Comment by kimrutherford** [comment]
> Also we can look at the chaperone prompts:

Is that covered by this issue:
  - https://github.com/pombase/pombase-config/issues/97

>  can you remind me how to do these next week , I think I remember one but not the other

Is this what you need?: https://github.com/pombase/pombase-config/issues/97#issuecomment-1711347948

**Comment by ValWood** [comment]
I added
        {
            "rel_name": "has_input",
            "if_descendant_of": "GO:0044183",
            "display_name": "chaperones",
            "reciprocal_display": "chaperoned by"
        },

for protein folding chaperone.

It seems that "protein carrier activity" has chaperones. But there must be some odd exceptions
because
[ATP-dependent H2AZ histone chaperone activity](https://www.pombase.org/term/GO:0140849)
appears as has_substrate, and I can't figure out why.

**Comment by ValWood** [comment]
(all of the other histone chaperones say chaperones...)

**Comment by kimrutherford** [comment]
I tried the new config on my desktop and it looks good: https://desktop.kmr.nz/term/GO:0044183

> [ATP-dependent H2AZ histone chaperone activity](https://www.pombase.org/term/GO:0140849)
> appears as has_substrate, and I can't figure out why.

It looks like it's because `has_input` is displayed as `has substrate` for descendents of GO:0003824
https://www.pombase.org/term/GO:0003824
https://github.com/pombase/pombase-config/blob/0a439cb45c92aee797cc59ec609eddbc6e6b66d7/website/pombase_v2_config.json#L5665-L5670

**Comment by ValWood** [comment]
Kim has fixed by moving up the config file so all "carrier chaperones" will have "chaperones"

**Comment by kimrutherford** [comment]
I think this is OK now.
