### ISSUE TITLE
Add GO:0140418 to range of 'involved in biological process' extension

### ISSUE THREAD

**Issue by jseager7** [pombase/pombase-config#95]
PHI-base has a curation session that needs the 'involved in biological process' annotation extension (see [here](https://github.com/pombase/pombase-config/blob/11b2b2503a1b2480f191c1507331ea5c5f117f49/canto/annotation_ex_config/GO_MF_A_E_config#L8)) on the GO term 'effector-mediated modulation of host process by symbiont' (GO:0140418).

This GO term doesn't seem to be a descendant of the currently specified terms (GO:0009987, GO:0045087, or GO:0052200).

@ValWood Would you have any problem with this term being added to the PomBase config? We'd be fine with using a parent term if there's anything applicable.

(CC @CuzickA)

**Comment by ValWood** [comment]
Yes we can add this. I think you can just do a pull request?

CC @kimrutherford
