### ISSUE TITLE
chaperone

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#97]
https://www.pombase.org/term/GO:0044183

display label has_input  can be "chaperones"

This term can also be added to the GO Molecular function slim (pombe and japonicus)

@kimrutherford  could you do this.
Next time we chat I want to get the website repository which will make this easier.

**Comment by ValWood** [comment]
No hurry for this.
Next week I can ge the repository and make sure it is documented so that I can do it. I always forget what is where.

**Comment by kimrutherford** [comment]
The Canto extension config docs are here: https://github.com/pombase/canto/wiki/AnnotationExtensionConfig

The website extension display docs are here: https://github.com/pombase/website/wiki/Config-file#extension_display_names

We can work on improving them next time we chat.

You should be able to get a copy of the configuration repo with:
```
git clone git@github.com:pombase/pombase-config.git
```

That will create a `pombase-config` directory.

The Canto extension config is in this directory:
```
pombase-config/canto/annotation_ex_config/
```

The website config is this file:
```
pombase-config/website/pombase_v2_config.json
```
